name=input("이름을 입력하시오:")
age=input("나이를 입력하시오:")
num=100000000000
a="제 이름은 {}이며 제 나이는{}입니다.".format(name,age)
b="제 이름은 {1}이며 제 나이는{0}입니다.".format(age,name)
c="{:=<30}".format(name)
d="{:>30}".format(name)
e="{:*^30}".format(name)
f="{:,}".format(num)
g="{:>30}".format(f)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)