num=[1,4,6,2,7,4,5,3,8,9]
num.sort()
print(num)
num.sort(reverse=True)
print(num)
num2=sorted(num)
num3=sorted(num, reverse=True)
print(f"num: {num}")
print(f"num2: {num2}")
print(f"num3: {num3}")